# Generated by Django 5.0 on 2023-12-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify date'),
        ),
    ]
