# Generated by Django 5.0 on 2023-12-30 01:58

import video_transmission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transmission', '0002_alter_video_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to=video_transmission.models.user_video_directory_path, verbose_name='Video File'),
        ),
    ]
