# Generated by Django 5.0 on 2023-12-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transmission', '0003_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_process_status',
            field=models.CharField(default='to_process', max_length=20, verbose_name='Video status'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_processed_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Video processed data'),
        ),
    ]
